name: movie_db
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  pull_to_refresh: 2.0.0
  cached_network_image: 3.2.3
  responsive_sizer: 3.1.1
  google_fonts: 4.0.3
  firebase_storage: 11.2.3
  firebase_core: 2.14.0
  firebase_auth: 4.6.3
  cloud_firestore: 4.8.1
  lottie: 2.2.0
  curved_navigation_bar: 1.0.3
  intl: 0.17.0
  google_sign_in: 5.4.2
  expandable: 5.0.1
  youtube_player_flutter: 8.1.2
  carousel_slider: 4.2.1
  flutter_launcher_icons: 0.13.1
  infinite_scroll_pagination: 3.2.0
  loading_animation_widget: 1.2.0+4
  email_validator: 2.1.17
  flutter_native_splash: 2.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/images/icon-playstore.png
  ios: true
  min_sdk_android: 21

flutter_native_splash: 
  android: true
  ios: true
  web: true
  image: "assets/images/icon-playstore.png"
  color: "#F9F5F6"


