name: movie_db
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  pull_to_refresh: 2.0.0
  cached_network_image: 3.2.3
  responsive_sizer: 3.1.1
  google_fonts: 4.0.3
  firebase_storage: 11.0.11
  firebase_core: 2.5.0
  firebase_auth: 4.2.6
  cloud_firestore: 4.4.0
  lottie: 2.2.0
  curved_navigation_bar: 1.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

