name: movie_db
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  persistent_bottom_nav_bar: 5.0.2
  http: 0.13.5
  pull_to_refresh: 2.0.0
  cached_network_image: 3.2.3
  responsive_sizer: 3.1.1
  google_fonts: 4.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

